/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SofiaOnboardingRouteImport } from './routes/sofia-onboarding'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as CronRouteImport } from './routes/cron'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as AgentWhatsappReportsRouteImport } from './routes/agent/whatsapp-reports'
import { Route as AgentWhatsappRouteImport } from './routes/agent/whatsapp'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentTemplatesRouteImport } from './routes/agent/templates'
import { Route as AgentTemplateEditorRouteImport } from './routes/agent/template-editor'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentSkillEditorRouteImport } from './routes/agent/skill-editor'
import { Route as AgentOrchestrationRouteImport } from './routes/agent/orchestration'
import { Route as AgentHubRouteImport } from './routes/agent/hub'
import { Route as AgentEditorRouteImport } from './routes/agent/editor'
import { Route as AgentAgentsRouteImport } from './routes/agent/agents'
import { Route as AdminCloneRouteImport } from './routes/admin/clone'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin/tenants/index'
import { Route as AdminTenantsNewRouteImport } from './routes/admin/tenants/new'
import { Route as AdminTenantsIdRouteImport } from './routes/admin/tenants/$id'

const SofiaOnboardingRoute = SofiaOnboardingRouteImport.update({
  id: '/sofia-onboarding',
  path: '/sofia-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const AgentWhatsappReportsRoute = AgentWhatsappReportsRouteImport.update({
  id: '/whatsapp-reports',
  path: '/whatsapp-reports',
  getParentRoute: () => AgentRoute,
} as any)
const AgentWhatsappRoute = AgentWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentTemplatesRoute = AgentTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AgentRoute,
} as any)
const AgentTemplateEditorRoute = AgentTemplateEditorRouteImport.update({
  id: '/template-editor',
  path: '/template-editor',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillEditorRoute = AgentSkillEditorRouteImport.update({
  id: '/skill-editor',
  path: '/skill-editor',
  getParentRoute: () => AgentRoute,
} as any)
const AgentOrchestrationRoute = AgentOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)
const AgentEditorRoute = AgentEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAgentsRoute = AgentAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AgentRoute,
} as any)
const AdminCloneRoute = AdminCloneRouteImport.update({
  id: '/admin/clone',
  path: '/admin/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsNewRoute = AdminTenantsNewRouteImport.update({
  id: '/admin/tenants/new',
  path: '/admin/tenants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/admin/tenants/$id',
  path: '/admin/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/cron': typeof CronRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/pendencias': typeof PendenciasRoute
  '/readiness': typeof ReadinessRoute
  '/sofia-onboarding': typeof SofiaOnboardingRoute
  '/admin/clone': typeof AdminCloneRoute
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/editor': typeof AgentEditorRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/orchestration': typeof AgentOrchestrationRoute
  '/agent/skill-editor': typeof AgentSkillEditorRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/template-editor': typeof AgentTemplateEditorRoute
  '/agent/templates': typeof AgentTemplatesRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/whatsapp': typeof AgentWhatsappRoute
  '/agent/whatsapp-reports': typeof AgentWhatsappReportsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/new': typeof AdminTenantsNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/cron': typeof CronRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/pendencias': typeof PendenciasRoute
  '/readiness': typeof ReadinessRoute
  '/sofia-onboarding': typeof SofiaOnboardingRoute
  '/admin/clone': typeof AdminCloneRoute
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/editor': typeof AgentEditorRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/orchestration': typeof AgentOrchestrationRoute
  '/agent/skill-editor': typeof AgentSkillEditorRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/template-editor': typeof AgentTemplateEditorRoute
  '/agent/templates': typeof AgentTemplatesRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/whatsapp': typeof AgentWhatsappRoute
  '/agent/whatsapp-reports': typeof AgentWhatsappReportsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/new': typeof AdminTenantsNewRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/cron': typeof CronRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/pendencias': typeof PendenciasRoute
  '/readiness': typeof ReadinessRoute
  '/sofia-onboarding': typeof SofiaOnboardingRoute
  '/admin/clone': typeof AdminCloneRoute
  '/agent/agents': typeof AgentAgentsRoute
  '/agent/editor': typeof AgentEditorRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/orchestration': typeof AgentOrchestrationRoute
  '/agent/skill-editor': typeof AgentSkillEditorRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/template-editor': typeof AgentTemplateEditorRoute
  '/agent/templates': typeof AgentTemplatesRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agent/whatsapp': typeof AgentWhatsappRoute
  '/agent/whatsapp-reports': typeof AgentWhatsappReportsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/new': typeof AdminTenantsNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/cron'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/memory'
    | '/models'
    | '/pendencias'
    | '/readiness'
    | '/sofia-onboarding'
    | '/admin/clone'
    | '/agent/agents'
    | '/agent/editor'
    | '/agent/hub'
    | '/agent/orchestration'
    | '/agent/skill-editor'
    | '/agent/skills'
    | '/agent/template-editor'
    | '/agent/templates'
    | '/agent/tools'
    | '/agent/whatsapp'
    | '/agent/whatsapp-reports'
    | '/channels/$name'
    | '/config/raw'
    | '/admin/'
    | '/admin/tenants/$id'
    | '/admin/tenants/new'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/cron'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/memory'
    | '/models'
    | '/pendencias'
    | '/readiness'
    | '/sofia-onboarding'
    | '/admin/clone'
    | '/agent/agents'
    | '/agent/editor'
    | '/agent/hub'
    | '/agent/orchestration'
    | '/agent/skill-editor'
    | '/agent/skills'
    | '/agent/template-editor'
    | '/agent/templates'
    | '/agent/tools'
    | '/agent/whatsapp'
    | '/agent/whatsapp-reports'
    | '/channels/$name'
    | '/config/raw'
    | '/admin'
    | '/admin/tenants/$id'
    | '/admin/tenants/new'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/cron'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/memory'
    | '/models'
    | '/pendencias'
    | '/readiness'
    | '/sofia-onboarding'
    | '/admin/clone'
    | '/agent/agents'
    | '/agent/editor'
    | '/agent/hub'
    | '/agent/orchestration'
    | '/agent/skill-editor'
    | '/agent/skills'
    | '/agent/template-editor'
    | '/agent/templates'
    | '/agent/tools'
    | '/agent/whatsapp'
    | '/agent/whatsapp-reports'
    | '/channels/$name'
    | '/config/raw'
    | '/admin/'
    | '/admin/tenants/$id'
    | '/admin/tenants/new'
    | '/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  CronRoute: typeof CronRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  PendenciasRoute: typeof PendenciasRoute
  ReadinessRoute: typeof ReadinessRoute
  SofiaOnboardingRoute: typeof SofiaOnboardingRoute
  AdminCloneRoute: typeof AdminCloneRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsNewRoute: typeof AdminTenantsNewRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sofia-onboarding': {
      id: '/sofia-onboarding'
      path: '/sofia-onboarding'
      fullPath: '/sofia-onboarding'
      preLoaderRoute: typeof SofiaOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/agent/whatsapp-reports': {
      id: '/agent/whatsapp-reports'
      path: '/whatsapp-reports'
      fullPath: '/agent/whatsapp-reports'
      preLoaderRoute: typeof AgentWhatsappReportsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/whatsapp': {
      id: '/agent/whatsapp'
      path: '/whatsapp'
      fullPath: '/agent/whatsapp'
      preLoaderRoute: typeof AgentWhatsappRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/templates': {
      id: '/agent/templates'
      path: '/templates'
      fullPath: '/agent/templates'
      preLoaderRoute: typeof AgentTemplatesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/template-editor': {
      id: '/agent/template-editor'
      path: '/template-editor'
      fullPath: '/agent/template-editor'
      preLoaderRoute: typeof AgentTemplateEditorRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skill-editor': {
      id: '/agent/skill-editor'
      path: '/skill-editor'
      fullPath: '/agent/skill-editor'
      preLoaderRoute: typeof AgentSkillEditorRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/orchestration': {
      id: '/agent/orchestration'
      path: '/orchestration'
      fullPath: '/agent/orchestration'
      preLoaderRoute: typeof AgentOrchestrationRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/editor': {
      id: '/agent/editor'
      path: '/editor'
      fullPath: '/agent/editor'
      preLoaderRoute: typeof AgentEditorRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/agents': {
      id: '/agent/agents'
      path: '/agents'
      fullPath: '/agent/agents'
      preLoaderRoute: typeof AgentAgentsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/clone': {
      id: '/admin/clone'
      path: '/admin/clone'
      fullPath: '/admin/clone'
      preLoaderRoute: typeof AdminCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/new': {
      id: '/admin/tenants/new'
      path: '/admin/tenants/new'
      fullPath: '/admin/tenants/new'
      preLoaderRoute: typeof AdminTenantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/admin/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentAgentsRoute: typeof AgentAgentsRoute
  AgentEditorRoute: typeof AgentEditorRoute
  AgentHubRoute: typeof AgentHubRoute
  AgentOrchestrationRoute: typeof AgentOrchestrationRoute
  AgentSkillEditorRoute: typeof AgentSkillEditorRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentTemplateEditorRoute: typeof AgentTemplateEditorRoute
  AgentTemplatesRoute: typeof AgentTemplatesRoute
  AgentToolsRoute: typeof AgentToolsRoute
  AgentWhatsappRoute: typeof AgentWhatsappRoute
  AgentWhatsappReportsRoute: typeof AgentWhatsappReportsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAgentsRoute: AgentAgentsRoute,
  AgentEditorRoute: AgentEditorRoute,
  AgentHubRoute: AgentHubRoute,
  AgentOrchestrationRoute: AgentOrchestrationRoute,
  AgentSkillEditorRoute: AgentSkillEditorRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentTemplateEditorRoute: AgentTemplateEditorRoute,
  AgentTemplatesRoute: AgentTemplatesRoute,
  AgentToolsRoute: AgentToolsRoute,
  AgentWhatsappRoute: AgentWhatsappRoute,
  AgentWhatsappReportsRoute: AgentWhatsappReportsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  CronRoute: CronRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  PendenciasRoute: PendenciasRoute,
  ReadinessRoute: ReadinessRoute,
  SofiaOnboardingRoute: SofiaOnboardingRoute,
  AdminCloneRoute: AdminCloneRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsNewRoute: AdminTenantsNewRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
