package api

import (
	"sync"
	"time"
)

// promotedPasswordTTL is how long after a successful promote the
// generated password can be re-displayed via the recent-password
// endpoint. Short on purpose: this is a "the admin closed the dialog
// before copying" lifeline, not a long-term retrieval mechanism.
const promotedPasswordTTL = 10 * time.Minute

// promotedPasswordEntry holds the generated password + expiry for a
// recently-promoted tenant. Stored in-memory only — restart of the
// controlplane drops the cache and the admin falls back to
// /resend-credentials (which rotates + emails a fresh one).
type promotedPasswordEntry struct {
	password  string
	expiresAt time.Time
}

// promotedPasswordCache is a one-shot in-memory cache mapping tenantID
// to the password generated by a recent /promote call. Audit P1 #23
// (2026-05-27): without this, an admin who closed the promote modal
// before copying the password had to call /resend-credentials which
// rotates AND emails (so the password they see is different from what
// the owner gets if the original promote email had been delivered).
// The cache lets the admin retrieve the SAME password for a brief
// window without rotating.
//
// One-shot semantics (read once and burn) + 10-min TTL keep the
// exposure window minimal. Concurrent admins racing for the same
// tenant's password get either-or, never both.
type promotedPasswordCache struct {
	mu      sync.Mutex
	entries map[string]promotedPasswordEntry
}

func newPromotedPasswordCache() *promotedPasswordCache {
	return &promotedPasswordCache{entries: make(map[string]promotedPasswordEntry)}
}

// Store records a password for tenantID, overwriting any prior entry
// (a second /promote for the same tenant during the TTL window
// supersedes the first — relevant for retries within the window).
func (c *promotedPasswordCache) Store(tenantID, password string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.entries[tenantID] = promotedPasswordEntry{
		password:  password,
		expiresAt: time.Now().Add(promotedPasswordTTL),
	}
	c.evictExpiredLocked()
}

// ConsumeOnce returns (password, true) if a non-expired entry exists
// AND deletes it atomically. Subsequent calls for the same tenantID
// return ("", false). Returns ("", false) for missing or expired
// entries.
func (c *promotedPasswordCache) ConsumeOnce(tenantID string) (string, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	entry, ok := c.entries[tenantID]
	if !ok {
		return "", false
	}
	delete(c.entries, tenantID)
	if time.Now().After(entry.expiresAt) {
		return "", false
	}
	return entry.password, true
}

// evictExpiredLocked drops expired entries on the side of every Store
// call so the map doesn't grow unboundedly for tenants whose passwords
// are never consumed (admin closed the tab and never opened the panel
// again). Cheap because it scans only the entries map (small — handful
// of recent promotions at most).
func (c *promotedPasswordCache) evictExpiredLocked() {
	now := time.Now()
	for k, v := range c.entries {
		if now.After(v.expiresAt) {
			delete(c.entries, k)
		}
	}
}
