package api

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/sipeed/picoclaw/internal/saas/store"
	"github.com/sipeed/picoclaw/internal/saas/tenant"
)

// baselineWorkspaceFS embeds the full canonical workspace template shipped
// with the binary. The bootstrap extracts it into the default workspace's
// home/ when the legacy /srv/picoclaw/workspace/ host path is not available.
// The embedded tree itself is copied from repo-level workspace/, so
// extraction maps runtime config files to home/ and canonical agent files to
// home/workspace/.
// See baseline-workspace/README.md for content rules and the sync flow.
//
// The directory contents are auto-generated by scripts/sync-baseline-workspace.py
// from the repo's top-level workspace/ tree on every `make generate` run, so
// changes to Sofia / Catarina / onboarding-state / any skill in workspace/
// propagate automatically to newly-bootstrapped tenants on the next image build.
//
//go:generate python3 ../../../scripts/sync-baseline-workspace.py
//go:embed all:baseline-workspace
var baselineWorkspaceFS embed.FS

// defaultWorkspaceSlug is the slug used for the bootstrap-created workspace.
const defaultWorkspaceSlug = "default-business"

// canonicalWorkspaceSource is the host path bind-mounted into the controlplane
// container at /srv/picoclaw:ro by docker-compose. When present, its contents
// are copied into the bootstrapped workspace's home/workspace/ so newly
// created tenants start from the canonical Jotaduo workspace.
const canonicalWorkspaceSource = "/srv/picoclaw/workspace"

// EnsureDefaultWorkspace creates a default-auto workspace on first run so
// the operator has a selectable template immediately after install.
// Idempotent: when a default-auto workspace already exists, this is a no-op.
// Failures are logged and returned so the controlplane startup can decide
// whether to keep going (recommended) or hard-fail on bootstrap issues —
// current behavior is to keep going with a WARN.
func (h *Handler) EnsureDefaultWorkspace(ctx context.Context) error {
	if h.Workspaces == nil {
		return nil
	}

	// Fast path: already have a default. Still run the additive seed/repair
	// step so installs bootstrapped by older binaries (flat home/AGENT.md
	// instead of home/workspace/AGENT.md) heal on the next startup.
	if existing, err := h.Workspaces.GetDefaultAuto(ctx); err == nil && existing != nil {
		if err := ensureDefaultWorkspaceDirs(existing.HostPath); err != nil {
			return fmt.Errorf("ensure default workspace dirs: %w", err)
		}
		if err := seedDefaultWorkspaceHome(filepath.Join(existing.HostPath, tenant.WorkspaceHomeSubdir)); err != nil {
			return fmt.Errorf("seed existing default workspace: %w", err)
		}
		return nil
	} else if err != nil && !errors.Is(err, store.ErrWorkspaceNotFound) {
		return fmt.Errorf("query default workspace: %w", err)
	}

	workspaceDir := h.Cfg.WorkspaceDir
	if workspaceDir == "" {
		return fmt.Errorf("PICOCLAW_WORKSPACE_DIR not configured; cannot bootstrap default workspace")
	}

	slug := defaultWorkspaceSlug
	hostPath := filepath.Join(workspaceDir, slug)

	if err := ensureDefaultWorkspaceDirs(hostPath); err != nil {
		return fmt.Errorf("ensure default workspace dirs: %w", err)
	}

	homeDir := filepath.Join(hostPath, tenant.WorkspaceHomeSubdir)
	if err := seedDefaultWorkspaceHome(homeDir); err != nil {
		return fmt.Errorf("seed default workspace home: %w", err)
	}

	ws := &store.Workspace{
		ID:                slug + "-" + randomHex(3),
		Name:              "Default Business",
		Slug:              slug,
		Description:       "Auto-bootstrapped default workspace. Edit via admin UI to customize the template used for new tenants.",
		HostPath:          hostPath,
		IsDefaultAuto:     true,
		IsAvailableManual: true,
	}
	if err := h.Workspaces.Insert(ctx, ws); err != nil {
		return fmt.Errorf("insert workspace row: %w", err)
	}

	log.Printf("bootstrap: created default workspace id=%s slug=%s host=%s", ws.ID, ws.Slug, ws.HostPath)
	return nil
}

func ensureDefaultWorkspaceDirs(hostPath string) error {
	for _, sub := range []string{
		tenant.WorkspaceHomeSubdir,
		tenant.WorkspaceFrontendSrcSubdir,
		tenant.WorkspaceFrontendDistSubdir,
	} {
		if err := os.MkdirAll(filepath.Join(hostPath, sub), 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", sub, err)
		}
	}
	return nil
}

func seedDefaultWorkspaceHome(homeDir string) error {
	if err := os.MkdirAll(homeDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", homeDir, err)
	}
	// Step 1: seed home/workspace/ from the canonical host source if mounted.
	// Keeps legacy installs that bind /srv/picoclaw:ro working unchanged.
	workspaceDest := filepath.Join(homeDir, "workspace")
	if _, err := os.Stat(workspaceDest); errors.Is(err, os.ErrNotExist) && isUsableDir(canonicalWorkspaceSource) {
		if err := copyDir(canonicalWorkspaceSource, workspaceDest); err != nil {
			log.Printf("WARN: bootstrap workspace: copy host %s -> %s failed (%v); will fall through to embed", canonicalWorkspaceSource, workspaceDest, err)
		}
	}

	// Step 2: older binaries extracted the embedded workspace flat into
	// home/. Preserve any operator edits in that shape by copying known
	// workspace content into home/workspace/ before the additive baseline fill.
	if err := repairLegacyFlatWorkspaceHome(homeDir); err != nil {
		return err
	}

	// Step 3: extract the embedded baseline into homeDir, skip-if-exists per
	// file. This fills in anything the host source/legacy repair missed:
	// .security.yml + config.json at the home/ root, and workspace/* files if
	// the host source wasn't usable.
	if err := extractEmbeddedBaseline(homeDir); err != nil {
		log.Printf("WARN: bootstrap workspace: embed extract failed: %v", err)
	}

	// Note: home/config.json comes from the embedded baseline (extracted in
	// step 2 above when missing). That config is a sanitized snapshot of the
	// canonical production tenant config — it carries the full agents.list
	// + dispatch.rules + channel_list + model_list with ${LITELLM_KEY} /
	// ${LITELLM_URL} placeholders the provisioner substitutes per tenant.
	// No Go-side baseline generation needed.

	return nil
}

// isUsableDir returns true when path exists and is a directory the caller
// can walk into. Errors other than "missing" are logged at WARN and the
// caller decides whether to fall back.
func isUsableDir(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			log.Printf("WARN: bootstrap workspace: stat %s: %v", path, err)
		}
		return false
	}
	return info.IsDir()
}

// extractEmbeddedBaseline writes the embedded baseline-workspace contents
// into dst, stripping the "baseline-workspace/" prefix and skipping the
// .gitkeep placeholders we only use to force go:embed to include empty
// directories. Runtime files that belong at $PICOCLAW_HOME stay in dst;
// everything else is routed under dst/workspace/. SKIPS files that already
// exist at the destination so the operator's hand-edited content is never
// overwritten — only missing files get filled in.
//
// auth.json gets stricter permissions (0o600) than the rest because it
// may end up holding OAuth tokens after the operator runs `picoclaw auth
// login <provider>` inside the container.
func extractEmbeddedBaseline(dst string) error {
	const embedRoot = "baseline-workspace"
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dst, err)
	}
	return fs.WalkDir(baselineWorkspaceFS, embedRoot, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == embedRoot {
			return nil
		}
		rel := strings.TrimPrefix(path, embedRoot+"/")
		targetRel, ok := embeddedBaselineTargetRel(rel)
		if !ok {
			return nil
		}
		target := filepath.Join(dst, filepath.FromSlash(targetRel))
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if filepath.Base(rel) == ".gitkeep" {
			// Make sure the parent dir exists, but skip the placeholder file
			// itself — it's only needed to coax go:embed into shipping the
			// empty directory.
			return os.MkdirAll(filepath.Dir(target), 0o755)
		}
		// Skip README.md — it's repo documentation, not content tenants need.
		if filepath.Base(rel) == "README.md" {
			return nil
		}
		// Skip-if-exists: never overwrite operator content. The bootstrap is
		// purely additive.
		if _, err := os.Stat(target); err == nil {
			return nil
		}
		data, err := baselineWorkspaceFS.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read embed %s: %w", path, err)
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", filepath.Dir(target), err)
		}
		mode := os.FileMode(0o644)
		base := filepath.Base(rel)
		if base == "auth.json" || base == "config.json" {
			// 0o600: auth.json carries OAuth tokens after `picoclaw auth
			// login`; config.json may carry third-party tokens (Telegram,
			// Discord, Matrix, …) once the operator wires channels up.
			// The per-tenant LiteLLM key lives in its own file
			// (/root/.picoclaw/litellm.key) loaded by the launcher.
			mode = 0o600
		}
		if err := os.WriteFile(target, data, mode); err != nil {
			return fmt.Errorf("write %s: %w", target, err)
		}
		return nil
	})
}

var embeddedBaselineHomeRootFiles = map[string]struct{}{
	".security.yml":         {},
	"auth.json":             {},
	"config.json":           {},
	"launcher_policy.json":  {},
	"ui-visibility.json":    {},
	"ui.config.fields.json": {},
}

func embeddedBaselineTargetRel(rel string) (string, bool) {
	rel = filepath.ToSlash(filepath.Clean(rel))
	if rel == "." || rel == "" {
		return "", false
	}
	if filepath.Base(rel) == "README.md" {
		return "", false
	}
	if strings.Contains(rel, "/") {
		return "workspace/" + rel, true
	}
	if _, ok := embeddedBaselineHomeRootFiles[rel]; ok {
		return rel, true
	}
	return "workspace/" + rel, true
}

func repairLegacyFlatWorkspaceHome(homeDir string) error {
	entries, err := os.ReadDir(homeDir)
	if err != nil {
		return fmt.Errorf("read home dir %s: %w", homeDir, err)
	}
	for _, entry := range entries {
		rel := entry.Name()
		targetRel, ok := embeddedBaselineTargetRel(rel)
		if !ok || !strings.HasPrefix(targetRel, "workspace/") {
			continue
		}
		src := filepath.Join(homeDir, rel)
		dst := filepath.Join(homeDir, filepath.FromSlash(targetRel))
		if entry.IsDir() {
			if err := copyDirMissing(src, dst); err != nil {
				return fmt.Errorf("repair flat workspace dir %s: %w", rel, err)
			}
			continue
		}
		if err := copyFileMissing(src, dst); err != nil {
			return fmt.Errorf("repair flat workspace file %s: %w", rel, err)
		}
	}
	return nil
}

// copyDir recursively copies src into dst, preserving file modes. Used only
// during workspace bootstrap; not a general-purpose helper.
func copyDir(src, dst string) error {
	srcInfo, err := os.Stat(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, srcInfo.Mode()); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		s := filepath.Join(src, entry.Name())
		d := filepath.Join(dst, entry.Name())
		if entry.IsDir() {
			if err := copyDir(s, d); err != nil {
				return err
			}
			continue
		}
		if err := copyFile(s, d); err != nil {
			return err
		}
	}
	return nil
}

func copyDirMissing(src, dst string) error {
	srcInfo, err := os.Stat(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, srcInfo.Mode().Perm()); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		s := filepath.Join(src, entry.Name())
		d := filepath.Join(dst, entry.Name())
		if entry.IsDir() {
			if err := copyDirMissing(s, d); err != nil {
				return err
			}
			continue
		}
		if err := copyFileMissing(s, d); err != nil {
			return err
		}
	}
	return nil
}

func copyFileMissing(src, dst string) error {
	if _, err := os.Stat(dst); err == nil {
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return copyFile(src, dst)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	info, err := in.Stat()
	if err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode())
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}
